---
title: "Assignment 3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##1

Random experiment - procedure with well-defined set of outcomes and can be repeated arbitrarily many times.

Event - Collection of possible outcomes

Sample space - set of all possible outcomes for an experiment 

##2.1
```{r}
library(tidyverse)

impute_by_median<-function(x){
mu<-median(x,na.rm=1) # first compute the median of x
impute_f<-function(z){ # coordinate-wise imputation
if(is.na(z)){
return(mu) # if z is na replace with mean
}else{
return(z) # otherwise leave in place
}
}
return(map_dbl(x,impute_f)) # apply the map function to impute across vector
}

v<-c(1,2,NA,4)
impute_by_median(v)
```
```{r}
x<- seq(0,10,0.1)
y<- 5*x+1
df_xy<-data.frame(x,y)
df_xy%>%head(5)
```
```{r}
df_xy%>%
mutate(z=map2_dbl(x,y,~.x+.y))
```

```{r}
sometimes_missing<-function(index, value){
  if(index %% 5 == 0){
    return(NA)
  }
  else{
    return(value)
  }
}

sometimes_missing(14, 25)
sometimes_missing(15, 25)
```
```{r}
df_xy_missing<- df_xy%>%
  mutate(y=map2_dbl(row_number(),y,sometimes_missing))
```

```{r}
df_xy_impute<-df_xy_missing%>%
  mutate(y=impute_by_median(y))
```

```{r}
df_xy<-df_xy%>%
mutate(source="original")

df_xy_missing<-df_xy_missing%>%
mutate(source="corrupted")

df_xy_impute<-df_xy_impute%>%
mutate(source="imputed")

df_combined<-rbind(df_xy,df_xy_missing,df_xy_impute)
```

```{r}
ggplot(df_combined,aes(x=x,y=y,color=source))+geom_point()+
facet_wrap(~source)+geom_smooth(method="lm")

```
##2.2
```{r}
install.packages("readxl")
```
```{r}
library(readxl) # load the readxl library
folder_path<-"C:/Users/joest/OneDrive/Documents/Actual Docs/Bristol/Scem/Assignment 3/"
file_name<-"HockeyLeague.xlsx" 
file_path<-paste(folder_path,file_name,sep="") # create the file_path
wins_data_frame<-read_excel(file_path,sheet="Wins") # read of a sheet from an xl file
wins_data_frame %>%
  select(1:5)%>%
  head(3)
```
### Tidying
```{r}
cols <- colnames(wins_data_frame)
cols[1] = "Team"
colnames(wins_data_frame)<-cols

wins_tidy<-wins_data_frame%>%
  pivot_longer(!Team,names_to = "Year", values_to = "Wins")%>%
  separate(Wins,into=c("Wins", "Total"),sep=" of ",convert=TRUE)

wins_tidy%>% dim() 
wins_tidy%>%head(5) 
  
  
```

```{r}
loss_data_frame<-read_excel(file_path,sheet="Losses")
cols <- colnames(loss_data_frame)
cols[1] = "Team"
colnames(loss_data_frame)<-cols

losses_tidy<-loss_data_frame%>%
  pivot_longer(!Team,names_to = "Year", values_to = "Losses")%>%
  separate(Losses,into=c("Losses", "Total"),sep=" of ", convert=TRUE)

losses_tidy%>% dim() 
losses_tidy%>%head(5) 
```
```{r}
hockey_df<-left_join(losses_tidy,wins_tidy) %>%
  mutate(Draws = Total-(Wins+Losses)) %>%
  mutate(Wins_rt = Wins/Total) %>%
  mutate(Losses_rt = Losses/Total) %>%
  mutate(Draws_rt = Draws/Total)

head(hockey_df, 3)
```

```{r}
hockey_summary<-hockey_df %>%
  group_by(Team) %>%
  summarise(
    mean_win = mean(Wins_rt,na.rm=1), med_win = median(Wins_rt,na.rm=1), mean_loss = mean(Losses_rt, na.rm=1), med_loss = median(Losses_rt, na.rm=1), mean_draw = mean(Draws_rt, na.rm=1), med_draw = median(Draws_rt, na.rm=1) 
  ) %>%
arrange(desc(med_win))

hockey_summary
```

